# Generated by Django 2.0.7 on 2018-07-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_camera_agent_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='agent_ip',
            new_name='agent_server',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='agent_username',
            new_name='agent_user',
        ),
    ]
