# Generated by Django 2.0.7 on 2018-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20180720_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='direction',
            field=models.CharField(choices=[('in', 'Entrada do município'), ('out', 'Saída do município'), ('even', 'Lado par da via'), ('odd', 'Lado ímpar da via'), ('free', 'Movimento livre (domo)'), ('sidewalk', 'Câmera de calçada')], help_text='Direção para a qual a câmera está apontada', max_length=8),
        ),
    ]
