# Generated by Django 3.1 on 2021-06-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180720_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedlicenseplate',
            name='data_filename',
            field=models.CharField(help_text='Nome do arquivo ZIP que contém a(s) imagem(s) utilizada(s) na identificação da placa do carro', max_length=256),
        ),
    ]
